import type { Metadata } from "next";
import "./globals.css";
import { Changa } from "next/font/google";
import { Navbar } from "@/components/layout/Navbar";
const changa = Changa({
  subsets: ["latin", "arabic"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-changa",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body className={` antialiased ${changa.className}`}>
        <Navbar />

        {children}
      </body>
    </html>
  );
}
